model:
  dir: "./MetaModels/Final/MetaNet_3x256_different_dim_T2P"
  input_shape: 300  # input shape, change it according to your data
  layers:
    - type: "Linear"
      in_features: 300  # Input shape
      out_features: 256
      activation: "ReLU"
      dropout: 0.3

    - type: "Linear"
      in_features: 256  # Input shape
      out_features: 256
      activation: "ReLU"
      dropout: 0.3
    
    - type: "Linear"
      in_features: 256  # Input shape
      out_features: 256
      activation: "ReLU"
      dropout: 0.3

    - type: "Linear"
      in_features: 256
      out_features: 150
base_models:
  list: "C:\\dis\\ProgressiveTransformersSLP\\meta_data\\DifferentDimmensions_T2P\\list_transformers.txt"
data:
  dir: "C:\\dis\\ProgressiveTransformersSLP\\meta_data\\DifferentDimmensions_T2P\\data"